version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "tasks_service"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  app:
    container_name: website
    restart: always
    build: ./
    ports:
        - '5050:5050'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres: